# -*- coding: utf-8 -*-

"""
    telesignverifyapi.models.sms_response

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class SMSResponse(object):

    """Implementation of the 'SMS Response' model.

    TODO: type model description here.

    Attributes:
        success (bool): TODO: type description here.
        description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success" : "success",
        "description" : "description"
    }

    def __init__(self,
                 success=None,
                 description=None):
        """Constructor for the SMSResponse class"""

        # Initialize members of the class
        self.success = success
        self.description = description


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        success = dictionary.get("success")
        description = dictionary.get("description")

        # Return an object of this model
        return cls(success,
                   description)


