# -*- coding: utf-8 -*-

"""
    telesignverifyapi.telesign_verify_api_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.verify_api_controller import VerifyAPIController
from .controllers.api_controller import APIController

class TelesignverifyapiClient(object):

    config = Configuration

    @lazy_property
    def verify_api(self):
        return VerifyAPIController()

    @lazy_property
    def client(self):
        return APIController()


    def __init__(self, 
                 customer_id = None,
                 api_key = None):
        if customer_id != None:
            Configuration.customer_id = customer_id
        if api_key != None:
            Configuration.api_key = api_key


