# -*- coding: utf-8 -*-

"""
    telesignverifyapi.controllers.api_controller

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from .base_controller import BaseController
from ..api_helper import APIHelper
from ..configuration import Configuration
from ..http.auth.custom_auth import CustomAuth

class APIController(BaseController):

    """A Controller to access Endpoints in the telesignverifyapi API."""


    def get_verify_api(self):
        """Does a GET request to /hello.

        TODO: type endpoint description here.

        Returns:
            void: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _query_builder = Configuration.base_uri
        _query_builder += '/hello'
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare and execute request
        _request = self.http_client.get(_query_url)
        CustomAuth.apply(_request)
        _context = self.execute_request(_request)
        self.validate_response(_context)
